import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { writeFileSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Obsidian only loads a single main.js, and there is no reliable file path to
// point `new Worker(...)` at (especially on mobile). So the zip worker is
// compiled on its own here, and its output is written as the *text* content
// of a generated .ts module. WorkerFather then imports that string and turns
// it into a real Worker via `new Worker(URL.createObjectURL(new Blob([...])))`.
const workerBuild = await esbuild.build({
	entryPoints: ['src/Workers/zipWorker/zip.worker.ts'],
	bundle: true,
	format: 'iife',
	target: 'es2021',
	write: false,
});

writeFileSync(
	'src/Workers/zipWorker/zip.worker.generated.ts',
	`export default ${JSON.stringify(workerBuild.outputFiles[0].text)};\n`,
);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
